# Generated by Django 2.2.9 on 2020-02-12 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_auto_20200212_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
