# Generated by Django 2.2.9 on 2020-02-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
        ('needs', '0004_need_proposed_means'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='proposed_patterns',
            field=models.ManyToManyField(to='patterns.Pattern'),
        ),
    ]
