# Generated by Django 2.2.9 on 2020-02-15 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0005_need_proposed_patterns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
