# Generated by Django 2.2.9 on 2020-02-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0006_auto_20200215_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='proposed_patterns',
        ),
    ]
