# Generated by Django 2.2.9 on 2020-02-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('needs', '0007_remove_need_proposed_patterns'),
        ('patterns', '0002_pattern_required_concepts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_activities', to='needs.Need')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patterns.Pattern')),
            ],
        ),
    ]
