# Generated by Django 2.2.9 on 2020-02-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='need',
            new_name='result_need',
        ),
    ]
