# Generated by Django 2.2.9 on 2020-02-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('activities', '0002_auto_20200215_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
