# Generated by Django 2.2.9 on 2020-02-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='required_concepts',
            field=models.ManyToManyField(to='concepts.Concept'),
        ),
    ]
